// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package gateway

import (
	"context"
	"github.com/88labs/andpad-engineer-training/2023/Gopi/backend/internal/domain/model/todo"
	"sync"
)

// Ensure, that TodoCommandsGatewayMock does implement TodoCommandsGateway.
// If this is not the case, regenerate this file with moq.
var _ TodoCommandsGateway = &TodoCommandsGatewayMock{}

// TodoCommandsGatewayMock is a mock implementation of TodoCommandsGateway.
//
//	func TestSomethingThatUsesTodoCommandsGateway(t *testing.T) {
//
//		// make and configure a mocked TodoCommandsGateway
//		mockedTodoCommandsGateway := &TodoCommandsGatewayMock{
//			CreateTodoFunc: func(ctx context.Context, newTodo *todo.NewTodo) (*todo.Todo, error) {
//				panic("mock out the CreateTodo method")
//			},
//		}
//
//		// use mockedTodoCommandsGateway in code that requires TodoCommandsGateway
//		// and then make assertions.
//
//	}
type TodoCommandsGatewayMock struct {
	// CreateTodoFunc mocks the CreateTodo method.
	CreateTodoFunc func(ctx context.Context, newTodo *todo.NewTodo) (*todo.Todo, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateTodo holds details about calls to the CreateTodo method.
		CreateTodo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NewTodo is the newTodo argument value.
			NewTodo *todo.NewTodo
		}
	}
	lockCreateTodo sync.RWMutex
}

// CreateTodo calls CreateTodoFunc.
func (mock *TodoCommandsGatewayMock) CreateTodo(ctx context.Context, newTodo *todo.NewTodo) (*todo.Todo, error) {
	if mock.CreateTodoFunc == nil {
		panic("TodoCommandsGatewayMock.CreateTodoFunc: method is nil but TodoCommandsGateway.CreateTodo was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		NewTodo *todo.NewTodo
	}{
		Ctx:     ctx,
		NewTodo: newTodo,
	}
	mock.lockCreateTodo.Lock()
	mock.calls.CreateTodo = append(mock.calls.CreateTodo, callInfo)
	mock.lockCreateTodo.Unlock()
	return mock.CreateTodoFunc(ctx, newTodo)
}

// CreateTodoCalls gets all the calls that were made to CreateTodo.
// Check the length with:
//
//	len(mockedTodoCommandsGateway.CreateTodoCalls())
func (mock *TodoCommandsGatewayMock) CreateTodoCalls() []struct {
	Ctx     context.Context
	NewTodo *todo.NewTodo
} {
	var calls []struct {
		Ctx     context.Context
		NewTodo *todo.NewTodo
	}
	mock.lockCreateTodo.RLock()
	calls = mock.calls.CreateTodo
	mock.lockCreateTodo.RUnlock()
	return calls
}
