package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"errors"

	graph "github.com/88labs/andpad-engineer-training/2023/Kumar/backend/internal/handler/graph/generated"
	"github.com/88labs/andpad-engineer-training/2023/Kumar/backend/internal/handler/graph/model"
	usecase_input "github.com/88labs/andpad-engineer-training/2023/Kumar/backend/internal/usecase/input"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	todo, err := r.todoCreator.CreateTodo(ctx, &usecase_input.TodoCreator{Text: input.Text})
	if err != nil {
		return nil, errors.New("error")
	}
	return &model.Todo{ID: todo.ID.String(), Text: todo.Text}, nil
}

func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) { //sample todo

	todos := []*model.Todo{
		{ID: "1", Text: "Buy groceries", User: &model.User{ID: "user123", Name: "John"}},
		{ID: "2", Text: "Complete homework", User: &model.User{ID: "user456", Name: "Jane"}},
	}
	return todos, nil
}

func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }
func (r *Resolver) Query() graph.QueryResolver       { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
