on:
  push:
    branches:
      - main
    paths:
      - '2023/Kumar/backend/**'
      - '.github/workflows/ci_kumar_backends.yml'
  pull_request:
    paths:
      - '2023/Kumar/backend/**'
      - '.github/workflows/ci_kumar_backends.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.4
      - name: Test
        run: make test
        working-directory: 2023/Kumar/backend